M48
; DRILL file KiCad 10.0.6 date 2026-09-20T10:49:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-20T10:49:32-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X19.61Y-6.4
X25.39Y-6.4
T2
X2.5Y-2.5
X2.5Y-37.5
M30
